name: ManualDependabot

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependabot:
    permissions:
      contents: write  # for Git to git push
      pull-requests: write  # for repo-sync/pull-request to create pull requests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Checkout dependabot
      run: |
        cd /tmp/
        git clone https://github.com/ertrzyiks/dependabot-script
    - name: Build image
      run: |
        cd /tmp/dependabot-script
        docker build -t "dependabot/dependabot-script" -f Dockerfile .
    - name: Run dependabot
      env:
        # Options can turn on extra features (not required)
        OPTIONS: |
           { "kubernetes_updates": true }
        GITHUB_ACCESS_TOKEN: ${{ github.token }}
        PROJECT_PATH: ertrzyiks/graph-utils
        PACKAGES_TO_CHECK: lerna
      run: |
        docker run -v $PWD:/src -e PROJECT_PATH=$PROJECT_PATH -e DIRECTORY=/ -e GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN -e OPTIONS="$OPTIONS" dependabot/dependabot-script
